Install development headers in CMake and compatible pkgconfig file
libsdl-org/sdl12-compat pull request #64
Opened 2021-05-24 19:06 UTC by Conan-Kudo

In order to fully substitute for SDL 1.2, we need to be able to
install the headers and generate a compatible .pc (pkgconfig) file.

There's an option to not install it if it is not desired for some
reason.

2021-05-24 19:28 UTC, Conan-Kudo commented
@icculus I discovered this while working on making packages that fully replace SDL in Fedora.

2021-05-26 05:54 UTC, Conan-Kudo commented
@icculus @sezero Any chance either of you could take a look at reviewing and (possibly) merging this?

2021-05-26 13:27 UTC, icculus requested changes
This looks fine, just need an answer on that VERSION 0.0.1 line.

2021-05-26 14:06 UTC, sezero commented on CMakeLists.txt
> +        LANGUAGES C CXX)
is CXX necessary here?

2021-05-26 14:07 UTC, Conan-Kudo commented on CMakeLists.txt
> +        VERSION 0.0.1
This is a separate version for this project itself. Everything that's "SDL-ish" is statically set to 1.2.50.

2021-05-26 14:08 UTC, Conan-Kudo commented on CMakeLists.txt
> +        LANGUAGES C CXX)
Nope, fixed! Thanks for catching that!

2021-05-26 15:24 UTC, Conan-Kudo commented
@icculus @sezero I think I've addressed all the feedback. 👍🏾

2021-05-26 22:27 UTC, merged